/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.user;
import model.pertanyaan;
import model.survei;
import model.jawaban;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
         // Array untuk menyimpan admin
    private static final ArrayList<user> userList = new ArrayList<>();
    private static final ArrayList<pertanyaan> pertanyaanList = new ArrayList<>();
    private static final ArrayList<survei> surveiList = new ArrayList<>();
    private static final ArrayList<jawaban> jawabanList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdUser = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        btnInputUser1 = new javax.swing.JButton();
        pnlSurvei = new javax.swing.JPanel();
        txtIdSurvei = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnInputSurvei = new javax.swing.JButton();
        txtDeskripsi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtWaktuMulai = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtWaktuSelesai = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtWaktuTenggat = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        pnlPertanyaan = new javax.swing.JPanel();
        txtIdPertanyaan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnInputPertanyaan = new javax.swing.JButton();
        txtIdSurvei2 = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlJawaban = new javax.swing.JPanel();
        txtIdJawaban = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInputJawaban = new javax.swing.JButton();
        txtIsi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnJawaban = new javax.swing.JButton();
        btnPertanyaan = new javax.swing.JButton();
        btnSurvei = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(0, 153, 153));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(pnlHome, "card6");

        pnlUser.setBackground(new java.awt.Color(0, 153, 153));
        pnlUser.setForeground(new java.awt.Color(255, 255, 255));
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        pnlUser.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 260, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Id User");
        pnlUser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nama");
        pnlUser.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 215, -1));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 260, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Username");
        pnlUser.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Password");
        pnlUser.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, -1));

        txtIdUser.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUserActionPerformed(evt);
            }
        });
        pnlUser.add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 260, 30));

        cmbRole.setBackground(new java.awt.Color(255, 255, 255));
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER", " ", " " }));
        pnlUser.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 260, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Role");
        pnlUser.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, -1));

        txtPassword1.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 260, 30));

        btnInputUser1.setText("INPUT");
        btnInputUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputUser1ActionPerformed(evt);
            }
        });
        pnlUser.add(btnInputUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 91, 41));

        Content.add(pnlUser, "card3");

        pnlSurvei.setBackground(new java.awt.Color(0, 153, 153));
        pnlSurvei.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdSurvei.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtIdSurvei, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 258, 30));

        txtJudul.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 258, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Id Survei");
        pnlSurvei.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Judul");
        pnlSurvei.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        btnInputSurvei.setText("INPUT");
        btnInputSurvei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputSurveiActionPerformed(evt);
            }
        });
        pnlSurvei.add(btnInputSurvei, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 91, 41));

        txtDeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 258, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Deskripsi");
        pnlSurvei.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 258, 30));

        jLabel27.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Status");
        pnlSurvei.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        txtWaktuMulai.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtWaktuMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 258, 30));

        jLabel28.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Waktu Mulai");
        pnlSurvei.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 180, -1));

        txtWaktuSelesai.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtWaktuSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 258, 30));

        jLabel29.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Waktu Selesai");
        pnlSurvei.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        txtWaktuTenggat.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurvei.add(txtWaktuTenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 258, 30));

        jLabel30.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Waktu Tenggat");
        pnlSurvei.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 190, -1));

        Content.add(pnlSurvei, "card4");

        pnlPertanyaan.setBackground(new java.awt.Color(0, 153, 153));
        pnlPertanyaan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdPertanyaan.setBackground(new java.awt.Color(255, 255, 255));
        pnlPertanyaan.add(txtIdPertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id Pertanyaan");
        pnlPertanyaan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 180, -1));

        btnInputPertanyaan.setText("INPUT");
        btnInputPertanyaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPertanyaanActionPerformed(evt);
            }
        });
        pnlPertanyaan.add(btnInputPertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 91, 41));

        txtIdSurvei2.setBackground(new java.awt.Color(255, 255, 255));
        pnlPertanyaan.add(txtIdSurvei2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 30));

        txtSection.setBackground(new java.awt.Color(255, 255, 255));
        pnlPertanyaan.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 260, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Id Survei");
        pnlPertanyaan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Section");
        pnlPertanyaan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 120, -1));

        Content.add(pnlPertanyaan, "card5");

        pnlJawaban.setBackground(new java.awt.Color(0, 153, 153));
        pnlJawaban.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdJawaban.setBackground(new java.awt.Color(255, 255, 255));
        pnlJawaban.add(txtIdJawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Jawaban");
        pnlJawaban.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 167, -1));

        btnInputJawaban.setText("INPUT");
        btnInputJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputJawabanActionPerformed(evt);
            }
        });
        pnlJawaban.add(btnInputJawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 91, 41));

        txtIsi.setBackground(new java.awt.Color(255, 255, 255));
        pnlJawaban.add(txtIsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 30));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Isi");
        pnlJawaban.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        Content.add(pnlJawaban, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 51, 51));
        Header.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("APLIKASI E-SURVEI");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 102, 102));
        Menu.setForeground(new java.awt.Color(51, 51, 51));

        btnJawaban.setBackground(new java.awt.Color(0, 153, 153));
        btnJawaban.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJawaban.setForeground(new java.awt.Color(0, 0, 0));
        btnJawaban.setText("JAWABAN");
        btnJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJawabanActionPerformed(evt);
            }
        });

        btnPertanyaan.setBackground(new java.awt.Color(0, 153, 153));
        btnPertanyaan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPertanyaan.setForeground(new java.awt.Color(0, 0, 0));
        btnPertanyaan.setText("PERTANYAAN");
        btnPertanyaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPertanyaanActionPerformed(evt);
            }
        });

        btnSurvei.setBackground(new java.awt.Color(0, 153, 153));
        btnSurvei.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSurvei.setForeground(new java.awt.Color(0, 0, 0));
        btnSurvei.setText("SURVEI");
        btnSurvei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurveiActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(0, 153, 153));
        btnUser.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnUser.setForeground(new java.awt.Color(0, 0, 0));
        btnUser.setText("USER");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPertanyaan)
                    .addComponent(btnSurvei)
                    .addComponent(btnUser)
                    .addComponent(btnJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnJawaban, btnPertanyaan, btnSurvei, btnUser});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPertanyaan)
                .addGap(18, 18, 18)
                .addComponent(btnSurvei)
                .addGap(18, 18, 18)
                .addComponent(btnUser)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnJawaban, btnPertanyaan, btnSurvei, btnUser});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputJawabanActionPerformed
        try {
            jawaban objJawaban = new jawaban();
            objJawaban.setId_jawaban(txtIdJawaban.getText());
            objJawaban.setText(txtIsi.getText());
            objJawaban.infoJawabanPopup();
            // Menambahkan objek ke dalam ArrayList
            jawabanList.add(objJawaban);

            // Memberi konfirmasi bahwa jawaban berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Jawaban berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua jawaban yang ada di ArrayList
            StringBuilder allJawaban = new StringBuilder("Daftar Jawaban:\n");
            for (jawaban jawaban : jawabanList) {
                allJawaban.append("ID Jawaban: ").append(jawaban.getId_jawaban())
                          .append("\n Isi: ").append(jawaban.getText())
                          .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allJawaban.toString(), 
                "Daftar Jawaban", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputJawabanActionPerformed

    private void btnInputPertanyaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPertanyaanActionPerformed
        try {
            pertanyaan objPertanyaan = new pertanyaan();
            objPertanyaan.setId_pertanyaan(txtIdPertanyaan.getText());
            objPertanyaan.setId_survei(txtIdSurvei2.getText());
            objPertanyaan.setSection(txtSection.getText());
            // Menambahkan objek ke dalam ArrayList
            pertanyaanList.add(objPertanyaan);

            // Memberi konfirmasi bahwa pertanyaan berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Pertanyaan berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua pertanyaan yang ada di ArrayList
            StringBuilder allPertanyaan = new StringBuilder("Daftar Pertanyaan:\n");
            for (pertanyaan pertanyaan : pertanyaanList) {
                allPertanyaan.append("ID Pertanyaan: ").append(pertanyaan.getId_pertanyaan())
                        .append("\n ID Survei: ").append(pertanyaan.getId_survei())
                        .append("\n Section: ").append(pertanyaan.getSection())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allPertanyaan.toString(), 
                "Daftar Jasa", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputPertanyaanActionPerformed

    private void btnInputSurveiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputSurveiActionPerformed
        try {
            survei objSurvei = new survei();
            objSurvei.setId_survei(txtIdSurvei.getText());
            objSurvei.setJudul(txtJudul.getText());
            objSurvei.setDeskripsi(txtDeskripsi.getText());
            objSurvei.setStatus(txtStatus.getText());
            objSurvei.setWaktu_mulai(txtWaktuMulai.getText());
            objSurvei.setWaktu_selesai(txtWaktuSelesai.getText());
            objSurvei.setWaktu_tenggat(txtWaktuTenggat.getText());
            objSurvei.infoSurveiPopup();
            // Menambahkan objek ke dalam ArrayList
            surveiList.add(objSurvei);

        // Memberi konfirmasi bahwa survei berhasil ditambahkan
        JOptionPane.showMessageDialog(null, 
            "Survei berhasil ditambahkan!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);

        // Menampilkan semua survei yang ada di ArrayList
        StringBuilder allSurvei = new StringBuilder("Daftar Survei:\n");
        for (survei survei : surveiList) {
            allSurvei.append("ID Survei : ").append(survei.getId_survei())
                    .append("\n Judul : ").append(survei.getJudul())
                    .append("\n Deskripsi : ").append(survei.getDeskripsi())
                    .append("\n Status : ").append(survei.getStatus())
                    .append("\n Waktu Mulai : ").append(survei.getWaktu_mulai())
                    .append("\n Waktu Selesai : ").append(survei.getWaktu_selesai())
                    .append("\n Waktu Tenggat : ").append(survei.getWaktu_tenggat())
                    .append("\n\n");
        }

        JOptionPane.showMessageDialog(null, allSurvei.toString(), 
            "Daftar Survei", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, 
            "Nominal harus berupa angka!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInputSurveiActionPerformed

    private void btnJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJawabanActionPerformed
        Content.removeAll(); 
        Content.add(pnlJawaban);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnJawabanActionPerformed

    private void btnPertanyaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPertanyaanActionPerformed
        Content.removeAll(); 
        Content.add(pnlPertanyaan);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPertanyaanActionPerformed

    private void btnSurveiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurveiActionPerformed
        Content.removeAll(); 
        Content.add(pnlSurvei);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnSurveiActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        Content.removeAll(); 
        Content.add(pnlUser);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUserActionPerformed

    private void btnInputUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputUser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputJawaban;
    private javax.swing.JButton btnInputPertanyaan;
    private javax.swing.JButton btnInputSurvei;
    private javax.swing.JButton btnInputUser1;
    private javax.swing.JButton btnJawaban;
    private javax.swing.JButton btnPertanyaan;
    private javax.swing.JButton btnSurvei;
    private javax.swing.JButton btnUser;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlJawaban;
    private javax.swing.JPanel pnlPertanyaan;
    private javax.swing.JPanel pnlSurvei;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtIdJawaban;
    private javax.swing.JTextField txtIdPertanyaan;
    private javax.swing.JTextField txtIdSurvei;
    private javax.swing.JTextField txtIdSurvei2;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtIsi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWaktuMulai;
    private javax.swing.JTextField txtWaktuSelesai;
    private javax.swing.JTextField txtWaktuTenggat;
    // End of variables declaration//GEN-END:variables
}
