/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataKonsumen(tabelKonsumen, "SELECT*FROM Konsumen");
        mycode.tampilDataPemesanan(tabelPemesanan, "SELECT*FROM Pemesanan");
        mycode.tampilDataKaryawan(tabelKaryawan, "SELECT*FROM Karyawan");
        mycode.tampilDataProduksi(tabelProduksi, "SELECT*FROM Produksi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlKaryawan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        btnHpsKrywn = new javax.swing.JButton();
        btnSmpnKrywn = new javax.swing.JButton();
        btnUbhKrywn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtCariKrywn = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        pnlKonsumen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnamaPerusahaan = new javax.swing.JTextField();
        txtidKonsumen = new javax.swing.JTextField();
        txtteleponPerusahaan = new javax.swing.JTextField();
        txtalamatPerusahaan = new javax.swing.JTextField();
        txtCariPrusahn = new javax.swing.JTextField();
        btnHpsPrusahn = new javax.swing.JButton();
        btnSmpnPrusahn = new javax.swing.JButton();
        btnUbhPrusahn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKonsumen = new javax.swing.JTable();
        pnlPemesanan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttglPemesanan = new javax.swing.JTextField();
        txtidPemesanan = new javax.swing.JTextField();
        txtidKaryawanPesan = new javax.swing.JTextField();
        txtidKonsumenPesan = new javax.swing.JTextField();
        txtCariPemesanan = new javax.swing.JTextField();
        btnHpsPmsanan = new javax.swing.JButton();
        btnSmpnPmsanan = new javax.swing.JButton();
        btnUbhPmsanan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPemesanan = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        pnlProduksi = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtidPemesananProduksi = new javax.swing.JTextField();
        txtidProduksi = new javax.swing.JTextField();
        txtidWilayah = new javax.swing.JTextField();
        txttglProduksi = new javax.swing.JTextField();
        txtCariProduksi = new javax.swing.JTextField();
        btnHpsPrdksi = new javax.swing.JButton();
        btnSmpnPrdksi = new javax.swing.JButton();
        btnUbhPrdksi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelProduksi = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtJumlahProduksi = new javax.swing.JTextField();
        txtidProduk = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKonsumen = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlKaryawan.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setText("Jabatan");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setText("Nama Karyawan");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setText("ID Karyawan");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btnHpsKrywn.setText("HAPUS");
        btnHpsKrywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKrywnActionPerformed(evt);
            }
        });

        btnSmpnKrywn.setText("SIMPAN");
        btnSmpnKrywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKrywnActionPerformed(evt);
            }
        });

        btnUbhKrywn.setText("UBAH");
        btnUbhKrywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKrywnActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setText("Password");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setText("No Telp");

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setText("Alamat");

        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        txtCariKrywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariKrywnActionPerformed(evt);
            }
        });
        txtCariKrywn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKrywnKeyReleased(evt);
            }
        });

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelKaryawan);

        javax.swing.GroupLayout pnlKaryawanLayout = new javax.swing.GroupLayout(pnlKaryawan);
        pnlKaryawan.setLayout(pnlKaryawanLayout);
        pnlKaryawanLayout.setHorizontalGroup(
            pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCariKrywn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .addGroup(pnlKaryawanLayout.createSequentialGroup()
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(56, 56, 56)
                                .addComponent(txtid))
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHpsKrywn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbhKrywn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSmpnKrywn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlKaryawanLayout.setVerticalGroup(
            pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(btnSmpnKrywn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(btnUbhKrywn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHpsKrywn))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(txtCariKrywn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        Content.add(pnlKaryawan, "card4");

        pnlKonsumen.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("No Telp Perusahaan");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Alamat Perusahaan");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Nama Perusahaan");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("ID Konsumen");

        txtidKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidKonsumenActionPerformed(evt);
            }
        });

        txtteleponPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponPerusahaanActionPerformed(evt);
            }
        });

        txtalamatPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatPerusahaanActionPerformed(evt);
            }
        });

        txtCariPrusahn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPrusahnKeyReleased(evt);
            }
        });

        btnHpsPrusahn.setText("HAPUS");
        btnHpsPrusahn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPrusahnActionPerformed(evt);
            }
        });

        btnSmpnPrusahn.setText("SIMPAN");
        btnSmpnPrusahn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPrusahnActionPerformed(evt);
            }
        });

        btnUbhPrusahn.setText("UBAH");
        btnUbhPrusahn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPrusahnActionPerformed(evt);
            }
        });

        tabelKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKonsumen);

        javax.swing.GroupLayout pnlKonsumenLayout = new javax.swing.GroupLayout(pnlKonsumen);
        pnlKonsumen.setLayout(pnlKonsumenLayout);
        pnlKonsumenLayout.setHorizontalGroup(
            pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonsumenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKonsumenLayout.createSequentialGroup()
                        .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidKonsumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtalamatPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSmpnPrusahn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbhPrusahn)
                            .addComponent(btnHpsPrusahn)))
                    .addGroup(pnlKonsumenLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(txtteleponPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCariPrusahn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlKonsumenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsPrusahn, btnSmpnPrusahn, btnUbhPrusahn});

        pnlKonsumenLayout.setVerticalGroup(
            pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonsumenLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSmpnPrusahn)))
                .addGap(13, 13, 13)
                .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUbhPrusahn))
                .addGap(13, 13, 13)
                .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamatPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsPrusahn))
                .addGap(12, 12, 12)
                .addGroup(pnlKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtteleponPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCariPrusahn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pnlKonsumenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHpsPrusahn, btnSmpnPrusahn, btnUbhPrusahn});

        Content.add(pnlKonsumen, "card3");

        pnlPemesanan.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("ID Karyawan ");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("ID Konsumen");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Tanggal Pemesanan");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("ID Pemesanan");

        txttglPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglPemesananActionPerformed(evt);
            }
        });

        txtCariPemesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPemesananKeyReleased(evt);
            }
        });

        btnHpsPmsanan.setText("HAPUS");
        btnHpsPmsanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPmsananActionPerformed(evt);
            }
        });

        btnSmpnPmsanan.setText("SIMPAN");
        btnSmpnPmsanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPmsananActionPerformed(evt);
            }
        });

        btnUbhPmsanan.setText("UBAH");
        btnUbhPmsanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPmsananActionPerformed(evt);
            }
        });

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelPemesanan);

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setText("Notes");

        javax.swing.GroupLayout pnlPemesananLayout = new javax.swing.GroupLayout(pnlPemesanan);
        pnlPemesanan.setLayout(pnlPemesananLayout);
        pnlPemesananLayout.setHorizontalGroup(
            pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPemesananLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel28)
                    .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCariPemesanan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                    .addGroup(pnlPemesananLayout.createSequentialGroup()
                        .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlPemesananLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPemesananLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(73, 73, 73)
                                    .addComponent(txtidPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtidKonsumenPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtidKaryawanPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbhPmsanan)
                            .addComponent(btnSmpnPmsanan)))
                    .addGroup(pnlPemesananLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(321, 321, 321)
                        .addComponent(btnHpsPmsanan)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlPemesananLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsPmsanan, btnSmpnPmsanan, btnUbhPmsanan});

        pnlPemesananLayout.setVerticalGroup(
            pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPemesananLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSmpnPmsanan)
                        .addComponent(txtidPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUbhPmsanan)
                        .addComponent(txttglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidKonsumenPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHpsPmsanan)))
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPemesananLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10))
                    .addGroup(pnlPemesananLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidKaryawanPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        Content.add(pnlPemesanan, "card5");

        pnlProduksi.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("ID Wilayah");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setText("Tanggal Produksi");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setText("ID Pemesanan");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setText("ID Produksi");

        txtidPemesananProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPemesananProduksiActionPerformed(evt);
            }
        });

        txtCariProduksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariProduksiKeyReleased(evt);
            }
        });

        btnHpsPrdksi.setText("HAPUS");
        btnHpsPrdksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPrdksiActionPerformed(evt);
            }
        });

        btnSmpnPrdksi.setText("SIMPAN");
        btnSmpnPrdksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPrdksiActionPerformed(evt);
            }
        });

        btnUbhPrdksi.setText("UBAH");
        btnUbhPrdksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPrdksiActionPerformed(evt);
            }
        });

        tabelProduksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelProduksi);

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setText("Jumlah Produksi");

        txtJumlahProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahProduksiActionPerformed(evt);
            }
        });

        txtidProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidProdukActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setText("ID Produk");

        javax.swing.GroupLayout pnlProduksiLayout = new javax.swing.GroupLayout(pnlProduksi);
        pnlProduksi.setLayout(pnlProduksiLayout);
        pnlProduksiLayout.setHorizontalGroup(
            pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduksiLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane3)
                    .addComponent(txtCariProduksi)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createSequentialGroup()
                        .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createSequentialGroup()
                                    .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(12, 12, 12))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(61, 61, 61))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduksiLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(68, 68, 68)))
                                    .addGap(12, 12, 12))
                                .addGroup(pnlProduksiLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(88, 88, 88)))
                            .addGroup(pnlProduksiLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(29, 29, 29)))
                        .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlahProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlProduksiLayout.createSequentialGroup()
                                    .addComponent(txttglProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnHpsPrdksi))
                                .addGroup(pnlProduksiLayout.createSequentialGroup()
                                    .addComponent(txtidProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnSmpnPrdksi))
                                .addComponent(txtidWilayah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlProduksiLayout.createSequentialGroup()
                                    .addComponent(txtidPemesananProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnUbhPrdksi))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pnlProduksiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsPrdksi, btnSmpnPrdksi, btnUbhPrdksi});

        pnlProduksiLayout.setVerticalGroup(
            pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduksiLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSmpnPrdksi)
                        .addComponent(txtidProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtidPemesananProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhPrdksi))
                .addGap(12, 12, 12)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttglProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsPrdksi))
                .addGap(12, 12, 12)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtidWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtidProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlProduksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtJumlahProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(txtCariProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Content.add(pnlProduksi, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI PERUSAHAAN TAMBANG");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(102, 255, 102));

        btnKonsumen.setBackground(new java.awt.Color(204, 204, 204));
        btnKonsumen.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKonsumen.setText("CUSTOMER");
        btnKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonsumenActionPerformed(evt);
            }
        });

        btnPemesanan.setBackground(new java.awt.Color(204, 204, 204));
        btnPemesanan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPemesanan.setText("PEMESANAN");
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });

        btnKaryawan.setBackground(new java.awt.Color(204, 204, 204));
        btnKaryawan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKaryawan.setText("KARYAWAN");
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnProduk.setBackground(new java.awt.Color(204, 204, 204));
        btnProduk.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnProduk.setText("PRODUKSI");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPemesanan)
                    .addComponent(btnKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKaryawan)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProduk)))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKaryawan, btnKonsumen, btnPemesanan, btnProduk});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPemesanan)
                .addGap(18, 18, 18)
                .addComponent(btnKaryawan)
                .addGap(18, 18, 18)
                .addComponent(btnProduk)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKaryawan, btnKonsumen, btnPemesanan, btnProduk});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonsumenActionPerformed
        Content.removeAll(); 
        Content.add(pnlKonsumen);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKonsumenActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        Content.removeAll(); 
        Content.add(pnlPemesanan);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        Content.removeAll(); 
        Content.add(pnlKaryawan);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        Content.removeAll(); 
        Content.add(pnlProduksi);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnSmpnPrusahnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPrusahnActionPerformed
        try {
            // --- 1. Validasi Input ---
            if (txtidKonsumen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Konsumen Belum Diisi");
                txtidKonsumen.requestFocus();
            } else if (txtnamaPerusahaan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Perusahaan Belum Diisi");
                txtnamaPerusahaan.requestFocus();
            } else if (txtalamatPerusahaan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Perusahaan Belum Diisi");
                txtalamatPerusahaan.requestFocus();
            } else if (txtteleponPerusahaan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Telepon Perusahaan Belum Diisi");
                txtteleponPerusahaan.requestFocus();
            } else {
                // --- 2. Panggil Metode Simpan ---
                mycode.simpanKonsumen(
                    txtidKonsumen.getText(), 
                    txtnamaPerusahaan.getText(), 
                    txtalamatPerusahaan.getText(), 
                    txtteleponPerusahaan.getText()
                );

                // --- 3. Periksa Duplikasi ---
                if (mycode.duplikasi == true){
                    // Jika duplikat, tampilkan data yang sudah ada di field (sesuai mapping di kelas crud)
                    txtnamaPerusahaan.setText(mycode.CEK_NAMA);       // CEK_NAMA = Nama_Perusahaan
                    txtalamatPerusahaan.setText(mycode.CEK_STATUS);    // CEK_STATUS = Alamat_Perusahaan
                    txtteleponPerusahaan.setText(mycode.CEK_TELP);     // CEK_TELP = No_Telp_Perusahaan
                }

                // --- 4. Refresh Data Tabel (Asumsi ada metode tampilDataKonsumen) ---
                mycode.tampilDataKonsumen(tabelKonsumen, "SELECT * FROM Konsumen");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Simpan Konsumen: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSmpnPrusahnActionPerformed

    private void btnUbhPrusahnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPrusahnActionPerformed
        try {
            if (txtidKonsumen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Konsumen Belum Diisi");
            } else {
                mycode.ubahKonsumen(
                    txtidKonsumen.getText(), 
                    txtnamaPerusahaan.getText(), 
                    txtalamatPerusahaan.getText(), 
                    txtteleponPerusahaan.getText()
                );

                // Refresh Data Tabel
                mycode.tampilDataKonsumen(tabelKonsumen, "SELECT * FROM Konsumen");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Ubah Konsumen: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbhPrusahnActionPerformed

    private void btnHpsPrusahnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPrusahnActionPerformed
        try {
            if (txtidKonsumen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Konsumen Belum Diisi");
            } else {
                 int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus data ID " + txtidKonsumen.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                 if (confirm == JOptionPane.YES_OPTION) {
                    mycode.hapusKonsumen(txtidKonsumen.getText());
                    // Refresh Data Tabel
                    mycode.tampilDataKonsumen(tabelKonsumen, "SELECT * FROM Konsumen");
                 }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Hapus Konsumen: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHpsPrusahnActionPerformed

    private void txtCariPrusahnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPrusahnKeyReleased
        String c = txtCariPrusahn.getText();
        String cari = "SELECT*FROM Konsumen WHERE ID_Konsumen LIKE '%"+c+"%'"+
                      "or Nama_Perusahaan LIKE '%"+c+"%' or Alamat_Perusahaan LIKE '%"+c+"%' or No_Telp_Perusahaan LIKE '%"+c+"%'";
        mycode.tampilDataKonsumen(tabelKonsumen, cari);
    }//GEN-LAST:event_txtCariPrusahnKeyReleased

    private void btnUbhPmsananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPmsananActionPerformed
        try {
            if (txtidPemesanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pemesanan Belum Diisi");
            } else {
                mycode.ubahPemesanan(
                    txtidPemesanan.getText(), 
                    txttglPemesanan.getText(), 
                    txtidKonsumenPesan.getText(), 
                    txtidKaryawanPesan.getText(), 
                    txtNotes.getText()
                );

                // Refresh Data Tabel
                mycode.tampilDataPemesanan(tabelPemesanan, "SELECT * FROM Pemesanan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Ubah Pemesanan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbhPmsananActionPerformed

    private void btnSmpnPmsananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPmsananActionPerformed
        try {
            // --- 1. Validasi Input ---
            if (txtidPemesanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pemesanan Belum Diisi");
                txtidPemesanan.requestFocus();
            } else if (txttglPemesanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Pemesanan Belum Diisi");
                txttglPemesanan.requestFocus();
            } else if (txtidKonsumenPesan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Konsumen Belum Diisi");
                txtidKonsumenPesan.requestFocus();
            } else {
                // --- 2. Panggil Metode Simpan ---
                mycode.simpanPemesanan(
                    txtidPemesanan.getText(), 
                    txttglPemesanan.getText(), 
                    txtidKonsumenPesan.getText(), 
                    txtidKaryawanPesan.getText(), // Asumsi ini diisi (bisa dari session login atau combobox)
                    txtNotes.getText()
                );

                // --- 3. Periksa Duplikasi ---
                if (mycode.duplikasi == true){
                    // Jika duplikat, tampilkan data yang sudah ada di field
                    txtidKonsumenPesan.setText(mycode.CEK_NAMA);     // CEK_NAMA = ID_Konsumen
                    txttglPemesanan.setText(mycode.CEK_STATUS);      // CEK_STATUS = Tanggal_Pemesanan
                    txtidKaryawanPesan.setText(mycode.CEK_TELP);     // CEK_TELP = ID_Karyawan
                }

                // --- 4. Refresh Data Tabel ---
                mycode.tampilDataPemesanan(tabelPemesanan, "SELECT * FROM Pemesanan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Simpan Pemesanan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSmpnPmsananActionPerformed

    private void btnHpsPmsananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPmsananActionPerformed
        try {
            if (txtidPemesanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pemesanan Belum Diisi");
            } else {
                 int confirm = JOptionPane.showConfirmDialog(null, "Menghapus Pemesanan juga dapat menghapus data di Produksi yang terkait! Lanjutkan?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                 if (confirm == JOptionPane.YES_OPTION) {
                    mycode.hapusPemesanan(txtidPemesanan.getText());
                    // Refresh Data Tabel
                    mycode.tampilDataPemesanan(tabelPemesanan, "SELECT * FROM Pemesanan");
                 }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Hapus Pemesanan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHpsPmsananActionPerformed

    private void txtCariPemesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPemesananKeyReleased
        String c = txtCariPemesanan.getText();
        String cari = "SELECT*FROM Pemesanan WHERE ID_Pemesanan LIKE '%"+c+"%'"+
                      "OR Tanggal_Pemesanan LIKE '%"+c+"%' OR ID_Konsumen LIKE '%"+c+"%'"+
                      "OR ID_Karyawan LIKE '%"+c+"%' OR Notes LIKE '%"+c+"%'";
        mycode.tampilDataPemesanan(tabelPemesanan, cari);
    }//GEN-LAST:event_txtCariPemesananKeyReleased

    private void txtCariProduksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariProduksiKeyReleased
        String c = txtCariProduksi.getText();
        String cari = "SELECT*FROM Produksi WHERE ID_Produksi LIKE '%"+c+"%'"+
                      "OR ID_Pemesanan LIKE '%"+c+"%' OR Tanggal_Produksi LIKE '%"+c+"%'"+
                      "OR ID_Wilayah LIKE '%"+c+"%' OR ID_Produk LIKE '%"+c+"%'"+
                      "OR Jumlah_Produksi LIKE '%"+c+"%'";
        mycode.tampilDataProduksi(tabelProduksi, cari);
    }//GEN-LAST:event_txtCariProduksiKeyReleased

    private void btnHpsPrdksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPrdksiActionPerformed
        try {
            if (txtidProduksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Produksi Belum Diisi");
            } else {
                 int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus data ID " + txtidProduksi.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                 if (confirm == JOptionPane.YES_OPTION) {
                    mycode.hapusProduksi(txtidProduksi.getText());
                    // Refresh Data Tabel
                    mycode.tampilDataProduksi(tabelProduksi, "SELECT * FROM Produksi");
                 }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Hapus Produksi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHpsPrdksiActionPerformed

    private void btnSmpnPrdksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPrdksiActionPerformed
        try {
            // --- 1. Validasi Input ---
            if (txtidProduksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Produksi Belum Diisi");
                txtidProduksi.requestFocus();
            } else if (txtidPemesananProduksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pemesanan Belum Diisi");
                txtidPemesananProduksi.requestFocus();
            } else if (txtJumlahProduksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jumlah Produksi Belum Diisi");
                txtJumlahProduksi.requestFocus();
            } else {
                // --- 2. Panggil Metode Simpan ---
                mycode.simpanProduksi(
                    txtidProduksi.getText(), 
                    txtidPemesananProduksi.getText(), 
                    txttglProduksi.getText(), 
                    txtidWilayah.getText(), 
                    txtidProduk.getText(),
                    txtJumlahProduksi.getText()
                );

                // --- 3. Periksa Duplikasi ---
                if (mycode.duplikasi == true){
                    // Jika duplikat, tampilkan data yang sudah ada di field
                    txtidPemesananProduksi.setText(mycode.CEK_NAMA);   // CEK_NAMA = ID_Pemesanan
                    txttglProduksi.setText(mycode.CEK_STATUS);         // CEK_STATUS = Tanggal_Produksi
                    txtidProduk.setText(mycode.CEK_TELP);              // CEK_TELP = ID_Produk
                }

                // --- 4. Refresh Data Tabel ---
                mycode.tampilDataProduksi(tabelProduksi, "SELECT * FROM Produksi");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Simpan Produksi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSmpnPrdksiActionPerformed

    private void btnUbhPrdksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPrdksiActionPerformed
        try {
            if (txtidProduksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Produksi Belum Diisi");
            } else {
                mycode.ubahProduksi(
                    txtidProduksi.getText(), 
                    txtidPemesananProduksi.getText(), 
                    txttglProduksi.getText(), 
                    txtidWilayah.getText(), 
                    txtidProduk.getText(),
                    txtJumlahProduksi.getText()
                );

                // Refresh Data Tabel
                mycode.tampilDataProduksi(tabelProduksi, "SELECT * FROM Produksi");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Ubah Produksi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbhPrdksiActionPerformed

    private void btnHpsKrywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKrywnActionPerformed
        try {
            if (txtid.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Karyawan Belum Diisi");
            } else {
                 int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus data ID " + txtid.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                 if (confirm == JOptionPane.YES_OPTION) {
                    mycode.hapusKaryawan(txtid.getText());
                    // Refresh Data Tabel
                    mycode.tampilDataKaryawan(tabelKaryawan, "SELECT * FROM Karyawan");
                 }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Hapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHpsKrywnActionPerformed

    private void btnSmpnKrywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKrywnActionPerformed
        try {
            // --- 1. Validasi Input ---
            if (txtid.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Karyawan Belum Diisi");
                txtid.requestFocus();
            } else if (txtnama.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtnama.requestFocus();
            } else if (txtjabatan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jabatan Belum Diisi");
                txtjabatan.requestFocus();
            } else if (txtalamat.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtalamat.requestFocus();
            } else if (txttelepon.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Telepon Belum Diisi");
                txttelepon.requestFocus();
            } else if (txtpassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Password Belum Diisi");
                txtpassword.requestFocus();
            } else {
                // --- 2. Panggil Metode Simpan ---
                mycode.simpanKaryawan(
                    txtid.getText(), 
                    txtnama.getText(), 
                    txtjabatan.getText(), 
                    txtalamat.getText(), 
                    txttelepon.getText(),
                    txtpassword.getText()
                );

                // --- 3. Periksa Duplikasi ---
                if (mycode.duplikasi == true){
                    // Jika duplikat, tampilkan data yang sudah ada di field
                    txtnama.setText(mycode.CEK_NAMA);
                    txtjabatan.setText(mycode.CEK_STATUS); // CEK_STATUS = Jabatan
                    txttelepon.setText(mycode.CEK_TELP);
                    // Catatan: Anda perlu mengambil Alamat dan Password secara manual jika ingin menampilkannya juga.
                }

                // --- 4. Refresh Data Tabel ---
                mycode.tampilDataKaryawan(tabelKaryawan, "SELECT * FROM Karyawan");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSmpnKrywnActionPerformed

    private void btnUbhKrywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKrywnActionPerformed
        try {
            if (txtid.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Karyawan Belum Diisi");
            } else {
                mycode.ubahKaryawan(
                    txtid.getText(), 
                    txtnama.getText(), 
                    txtjabatan.getText(), 
                    txtalamat.getText(), 
                    txttelepon.getText(),
                    txtpassword.getText()
                );

                // Refresh Data Tabel
                mycode.tampilDataKaryawan(tabelKaryawan, "SELECT * FROM Karyawan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Ubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbhKrywnActionPerformed

    private void txtCariKrywnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKrywnKeyReleased
        String c = txtCariKrywn.getText();
        String cari = "SELECT*FROM Karyawan WHERE ID_Karyawan LIKE '%"+c+"%'"+
                      "OR Nama_Karyawan LIKE '%"+c+"%' OR Jabatan LIKE '%"+c+"%'"+
                      "OR Alamat_Karyawan LIKE '%"+c+"%' OR No_Telp_Karyawan LIKE '%"+c+"%'"+
                      "OR Password LIKE '%"+c+"%'";
        mycode.tampilDataKaryawan(tabelKaryawan, cari);
    }//GEN-LAST:event_txtCariKrywnKeyReleased

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtCariKrywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariKrywnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKrywnActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKonsumenActionPerformed

    private void txtalamatPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatPerusahaanActionPerformed

    private void txttglPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglPemesananActionPerformed

    private void txtJumlahProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahProduksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahProduksiActionPerformed

    private void txtidProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidProdukActionPerformed

    private void txtidPemesananProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPemesananProduksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPemesananProduksiActionPerformed

    private void txtteleponPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponPerusahaanActionPerformed

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsKrywn;
    private javax.swing.JButton btnHpsPmsanan;
    private javax.swing.JButton btnHpsPrdksi;
    private javax.swing.JButton btnHpsPrusahn;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKonsumen;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSmpnKrywn;
    private javax.swing.JButton btnSmpnPmsanan;
    private javax.swing.JButton btnSmpnPrdksi;
    private javax.swing.JButton btnSmpnPrusahn;
    private javax.swing.JButton btnUbhKrywn;
    private javax.swing.JButton btnUbhPmsanan;
    private javax.swing.JButton btnUbhPrdksi;
    private javax.swing.JButton btnUbhPrusahn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKaryawan;
    private javax.swing.JPanel pnlKonsumen;
    private javax.swing.JPanel pnlPemesanan;
    private javax.swing.JPanel pnlProduksi;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JTable tabelKonsumen;
    private javax.swing.JTable tabelPemesanan;
    private javax.swing.JTable tabelProduksi;
    private javax.swing.JTextField txtCariKrywn;
    private javax.swing.JTextField txtCariPemesanan;
    private javax.swing.JTextField txtCariProduksi;
    private javax.swing.JTextField txtCariPrusahn;
    private javax.swing.JTextField txtJumlahProduksi;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtalamatPerusahaan;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidKaryawanPesan;
    private javax.swing.JTextField txtidKonsumen;
    private javax.swing.JTextField txtidKonsumenPesan;
    private javax.swing.JTextField txtidPemesanan;
    private javax.swing.JTextField txtidPemesananProduksi;
    private javax.swing.JTextField txtidProduk;
    private javax.swing.JTextField txtidProduksi;
    private javax.swing.JTextField txtidWilayah;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamaPerusahaan;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txtteleponPerusahaan;
    private javax.swing.JTextField txttglPemesanan;
    private javax.swing.JTextField txttglProduksi;
    // End of variables declaration//GEN-END:variables
}
